name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

env:
  DOCKER_FILE_PATH: Dockerfile
  GOLANG_VERSION: 1.18

jobs:
  CI:
    runs-on: ubuntu-latest
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Set up Go
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    # Run Linter
    - name: Lint
      uses: golangci/golangci-lint-action@v2.3.0
      with:
        version: v1.46.2
        only-new-issues: false
        args: --timeout 10m

    # Run Preliminary code tests
    - name: GOLANG Static code Analysis
      run: make vet

    # Run Vulnerability analysis tests
    - name: Run Snyk for Code Vulnerability Analysis
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: code test
        args: --severity-threshold=low --print-deps --detection-depth=2 --sarif-file-output=snyk.sarif

    # Run Tests
    - name: Test
      run: make test

    # Generate Tag for Image
    - name: Generate Tag
      id: generate_tag
      run: |
        sha=${{ github.event.pull_request.head.sha }}
        tag="SNAPSHOT-PR-${{ github.event.pull_request.number }}-${sha:0:8}"
        echo "##[set-output name=GIT_TAG;]$(echo ${tag})"
      
    # Setup Emulator
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # Setup docker buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Setup docker buildx
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Generate docker tag
    - name: Generate image repository path
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

    # Push Image to Image registry
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.DOCKER_FILE_PATH  }}
        pull: true
        push: true
        build-args: GIT_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
        cache-to: type=inline
        tags: |
          ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.GIT_TAG }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}

    # Image Scanning
    - name: Run Snyk to check Image for vulnerabilities
      uses: snyk/actions/docker@master 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.IMAGE_REPOSITORY }}:${{ steps.generate_tag.outputs.GIT_TAG }}

    # Generate manifests for the latest semver tag
    - name: Bump Version
      env:
        VERSION: ${{ steps.generate_tag.outputs.new_tag }}
      run: make manifests

    # Run Snyk for IaC assessment
    - name: Run Snyk to check configuration files for security issues
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        file: kubernetes/
        args: --severity-threshold=medium

    # Upload results
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif

    - name: Comment on PR
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: '@${{ github.actor }} Build Passed!! Image is available for testing! `docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ steps.generate_tag.outputs.GIT_TAG }}`'
        allow-repeats: false

    - name: Notify Failure
      if: failure()
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: '@${{ github.actor }} Build Failed!! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!'
        allow-repeats: false

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      if: always() # Pick up events even if the job fails or is canceled.
      with:
        status: ${{ job.status }}
        fields: repo,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}